### ISSUE TITLE
Documentation on Dockerizing AdonisJS incomplete

### ISSUE THREAD

**Issue by gdog2u** [adonisjs/v5-docs#224]
### Package version

n/a

### Describe the bug

The documentation for [/Cookbooks/dockerize-adonis/](https://github.com/adonisjs/docs.adonisjs.com/blob/develop/content/cookbooks/deployment/dockerizing-adonis.md) is incomplete by omitting what to do about the `APP_KEY` value. Following the instructions verbatim, and copy/pasting the config files here verbatim will result in the following output in the container's log.

```
2023-08-29 14:10:18 Exception: E_MISSING_ENV_VALUE: Missing environment variable "APP_KEY"
2023-08-29 14:10:18     at ensureValue (/home/node/app/node_modules/@adonisjs/env/build/src/Schema/helpers.js:26:15)
2023-08-29 14:10:18     at Object.validate [as APP_KEY] (/home/node/app/node_modules/@adonisjs/env/build/src/Schema/string.js:45:35)
2023-08-29 14:10:18     at /home/node/app/node_modules/@adonisjs/env/build/src/Env/index.js:87:60
2023-08-29 14:10:18     at Array.forEach (<anonymous>)
2023-08-29 14:10:18     at Env.process (/home/node/app/node_modules/@adonisjs/env/build/src/Env/index.js:86:44)
2023-08-29 14:10:18     at Application.loadEnvironmentVariables (/home/node/app/node_modules/@adonisjs/application/build/src/Application.js:303:18)
2023-08-29 14:10:18     at Application.setup (/home/node/app/node_modules/@adonisjs/application/build/src/Application.js:518:14)
2023-08-29 14:10:18     at AppKernel.boot (/home/node/app/node_modules/@adonisjs/core/build/src/Ignitor/Kernel/index.js:55:32)
2023-08-29 14:10:18     at HttpServer.start (/home/node/app/node_modules/@adonisjs/core/build/src/Ignitor/HttpServer/index.js:85:31)
2023-08-29 14:10:18     at Object.<anonymous> (/home/node/server.ts:21:4)
2023-08-29 14:11:34 {"level":30,"time":1693332694392,"pid":8,"hostname":"4cbf60af4c7b","name":"my-project-api","msg":"started server on 0.0.0.0:3333"}
```

The `APP_KEY` value is never mentioned in this guide.

**Comment by RomainLanz** [comment]
It does seem like generating a new one and setting it would be the straightforward approach. If you have ideas on how we can articulate this better or any enhancements in mind, I'd warmly welcome a Pull Request from you.
